# Generated by Django 2.2 on 2019-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='card2head',
            field=models.CharField(blank=True, default='sample', max_length=50),
        ),
    ]
