# Generated by Django 2.2 on 2019-12-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpply', '0003_auto_20191217_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='card1cont',
            field=models.CharField(blank=True, default='sample', max_length=50),
        ),
        migrations.AddField(
            model_name='info',
            name='card2cont',
            field=models.CharField(blank=True, default='sample', max_length=50),
        ),
        migrations.AddField(
            model_name='info',
            name='card3cont',
            field=models.CharField(blank=True, default='sample', max_length=50),
        ),
        migrations.AddField(
            model_name='info',
            name='card4cont',
            field=models.CharField(blank=True, default='sample', max_length=50),
        ),
    ]
